Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 3/24/2024
Var
    somatorio, contador: inteiro
Inicio
contador := 450
somatorio := 500

enquanto contador >= 0 faca
  somatorio := somatorio + contador
  contador := contador - 50
fimenquanto

escreval(somatorio)

Fimalgoritmo