Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 3/24/2024
Var
    somatorio, contador: inteiro
Inicio
contador := 8
somatorio := 6

enquanto contador <= 100 faca
  somatorio := somatorio + contador
  contador := contador + 2
fimenquanto

escreval(somatorio)

Fimalgoritmo