Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/2/2023
Var
numero: real

Inicio
escreval("Digite um número")
leia(numero)

se (numero % 2 = 0) entao
   escreval("O número é par")
senao
   escreval("O número é impar")
fimse

Fimalgoritmo