Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/2/2023
Var
ano: inteiro

Inicio
escreval("Digite o ano: ")
leia(ano)

se (ano % 4 = 0) entao
  escreval("O ano é bissexto")
senao
  escreval("o ano não é bissexto")
fimse
Fimalgoritmo