Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/05/2023
Var
// Seção de Declarações das variáveis 
nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Qual é o seu nome?")
leia(nome)

escreval("Olá ", nome, " é um prazer te conhecer!")

Fimalgoritmo